### ISSUE TITLE
tft_config.py : wrong PIN assignment?

### ISSUE THREAD

**Issue by fundef1** [Xinyuan-LilyGO/T-Dongle-S3#2]
Hi,
i'm having trouble getting the display to work, and while double checking I found the following:

on the schematic and in other bits of code, LEDA (backlight?) is assigned to pin 38
#define TFT_LEDA_PIN   38

in python it is PIN 37
      backlight=Pin(37, Pin.OUT),

setting backlight to pin38 seems to make tft.on() and tft.off() work, albeit reversed... it's active low i.e. tft.on() switches the backlight off.

**Comment by Xendi** [comment]
Also, I found that the fonts are not loaded in the firmware, you have to get them from somewhere else - e.g. the hello.py example works if I upload https://github.com/VynDragon/WPOS/blob/master/vga1_bold_16x32.py to the board first.

**Comment by Xendi** [comment]
> @Xendi, did you get the display to work? I am starting to think mine was DOA.

Can you run hello.py with the font uploaded? If not then yeah it might be.

**Comment by mmMicky** [comment]
If you use the mpy firmware provided by lilygo, it already contains the modified st7735 driver. Fonts can be read by dragging and dropping them into the file system.

**Comment by fundef1** [comment]
> If you use the mpy firmware provided by lilygo, it already contains the modified st7735 driver. Fonts can be read by dragging and dropping them into the file system.

which 'mpy' firmware are you referring to? I flashed to .bin from here
https://github.com/Xinyuan-LilyGO/T-Dongle-S3/tree/main/example/Micropython/firmware

which contains the tft_config.py with the wrong PIN assignment for the backlight.

(also: what do you use to drag & drop , i'm copying files across with mpremote - which is a bit tedious)

**Comment by mmMicky** [comment]
Problem seems to be resolved. I will close this issue
