### ISSUE TITLE
TFT.ino in example/TFT does not draw to screen

### ISSUE THREAD

**Issue by LockManipulator** [Xinyuan-LilyGO/T-Dongle-S3#5]
Using latest Arduino IDE. TFT_eSPI library is installed. girl.h, logo.h, logo2.h, pin_config.h are all in the same folder as TFT.ino. Code will upload but display remains on and blank. Please include all details needed to draw to the screen. Are there any config files that need to be changed?

**Comment by mmMicky** [comment]
I'm guessing you're in download mode. Please unplug the device and be careful not to hold down the key while reconnecting to run user code.

**Comment by LockManipulator** [comment]
I plugged it in without holding down the key and the code still does not run.

**Comment by mmMicky** [comment]
Did you recognize the serial port? Do you have a serial port software like this? This software is downloaded from Microsoft.
![image](https://user-images.githubusercontent.com/63094275/206352509-0387790c-ef92-4a29-9fcc-1c0da172abe2.png)

**Comment by LockManipulator** [comment]
The serial port is recognized. The code will upload successfully. But will not draw to screen. I can upload code to print to serial and that will run, so I know I can upload and run code. But nothing, including the example codes on github, will draw to screen. I can only turn the screen backlight on and off.

**Comment by mmMicky** [comment]
Is the screen damaged. I upload a test firmware for you to test.
[测试程序.zip](https://github.com/Xinyuan-LilyGO/T-Dongle-S3/files/10183419/default.zip)

**Comment by LockManipulator** [comment]
Screen is not damaged. I uploaded the firmware you posted and when I plug in the USB there is a logo of "LILYGO" and the led light changes colors. But the TFT.ino code still doesn't won't work if I upload it onto the esp32.

**Comment by LockManipulator** [comment]
I did a fresh install of everything and redownloaded all the files in "lib" and now it's working. I guess just a fresh install of Arduino IDE and all files for this project fixed it.
